// Dutch-Catalan Flashcard Data
// ~140 cards covering CEFR A1 and A2 topics

const CARDS = [

  // ── A1 · Salutacions ──────────────────────────────────────────────────────
  { id: "a1_hallo", level: "A1", topic: "Salutacions", dutch: "hallo", catalan: "hola",
    example: "Hallo, hoe gaat het?", exampleTranslation: "Hola, com estàs?" },
  { id: "a1_goedendag", level: "A1", topic: "Salutacions", dutch: "goedendag", catalan: "bon dia / bona tarda",
    example: "Goedendag, meneer.", exampleTranslation: "Bon dia, senyor." },
  { id: "a1_goedemorgen", level: "A1", topic: "Salutacions", dutch: "goedemorgen", catalan: "bon dia (al matí)",
    example: "Goedemorgen! Heb je goed geslapen?", exampleTranslation: "Bon dia! Has dormit bé?" },
  { id: "a1_goedemiddag", level: "A1", topic: "Salutacions", dutch: "goedemiddag", catalan: "bona tarda",
    example: "Goedemiddag, hoe gaat het?", exampleTranslation: "Bona tarda, com va?" },
  { id: "a1_goedenavond", level: "A1", topic: "Salutacions", dutch: "goedenavond", catalan: "bona nit (en arribar)",
    example: "Goedenavond, welkom!", exampleTranslation: "Bona nit, benvingut!" },
  { id: "a1_dag", level: "A1", topic: "Salutacions", dutch: "dag", catalan: "hola / adeu",
    example: "Dag! Tot ziens!", exampleTranslation: "Adeu! Fins aviat!" },
  { id: "a1_tot_ziens", level: "A1", topic: "Salutacions", dutch: "tot ziens", catalan: "fins aviat / adeu",
    example: "Tot ziens, tot morgen!", exampleTranslation: "Fins aviat, fins demà!" },
  { id: "a1_tot_later", level: "A1", topic: "Salutacions", dutch: "tot later", catalan: "fins després",
    example: "Ik ga nu. Tot later!", exampleTranslation: "Me'n vaig ara. Fins després!" },
  { id: "a1_alsjeblieft", level: "A1", topic: "Salutacions", dutch: "alsjeblieft", catalan: "si us plau",
    example: "Een koffie, alsjeblieft.", exampleTranslation: "Un cafè, si us plau." },
  { id: "a1_dankjewel", level: "A1", topic: "Salutacions", dutch: "dankjewel", catalan: "gràcies",
    example: "Dankjewel voor je hulp!", exampleTranslation: "Gràcies per la teva ajuda!" },

  // ── A1 · Números ─────────────────────────────────────────────────────────
  { id: "a1_een", level: "A1", topic: "Números", dutch: "één", catalan: "un / una" },
  { id: "a1_twee", level: "A1", topic: "Números", dutch: "twee", catalan: "dos / dues" },
  { id: "a1_drie", level: "A1", topic: "Números", dutch: "drie", catalan: "tres" },
  { id: "a1_vier", level: "A1", topic: "Números", dutch: "vier", catalan: "quatre" },
  { id: "a1_vijf", level: "A1", topic: "Números", dutch: "vijf", catalan: "cinc" },
  { id: "a1_zes", level: "A1", topic: "Números", dutch: "zes", catalan: "sis" },
  { id: "a1_zeven", level: "A1", topic: "Números", dutch: "zeven", catalan: "set" },
  { id: "a1_acht", level: "A1", topic: "Números", dutch: "acht", catalan: "vuit" },
  { id: "a1_negen", level: "A1", topic: "Números", dutch: "negen", catalan: "nou" },
  { id: "a1_tien", level: "A1", topic: "Números", dutch: "tien", catalan: "deu" },
  { id: "a1_elf", level: "A1", topic: "Números", dutch: "elf", catalan: "onze" },
  { id: "a1_twaalf", level: "A1", topic: "Números", dutch: "twaalf", catalan: "dotze" },
  { id: "a1_dertien", level: "A1", topic: "Números", dutch: "dertien", catalan: "tretze" },
  { id: "a1_veertien", level: "A1", topic: "Números", dutch: "veertien", catalan: "catorze" },
  { id: "a1_vijftien", level: "A1", topic: "Números", dutch: "vijftien", catalan: "quinze" },
  { id: "a1_zestien", level: "A1", topic: "Números", dutch: "zestien", catalan: "setze" },
  { id: "a1_zeventien", level: "A1", topic: "Números", dutch: "zeventien", catalan: "disset" },
  { id: "a1_achttien", level: "A1", topic: "Números", dutch: "achttien", catalan: "divuit" },
  { id: "a1_negentien", level: "A1", topic: "Números", dutch: "negentien", catalan: "dinou" },
  { id: "a1_twintig", level: "A1", topic: "Números", dutch: "twintig", catalan: "vint" },

  // ── A1 · Dies de la setmana ───────────────────────────────────────────────
  { id: "a1_maandag", level: "A1", topic: "Dies de la setmana", dutch: "maandag", catalan: "dilluns",
    example: "Op maandag werk ik.", exampleTranslation: "El dilluns treballo." },
  { id: "a1_dinsdag", level: "A1", topic: "Dies de la setmana", dutch: "dinsdag", catalan: "dimarts",
    example: "Op dinsdag heb ik les.", exampleTranslation: "El dimarts tinc classe." },
  { id: "a1_woensdag", level: "A1", topic: "Dies de la setmana", dutch: "woensdag", catalan: "dimecres" },
  { id: "a1_donderdag", level: "A1", topic: "Dies de la setmana", dutch: "donderdag", catalan: "dijous" },
  { id: "a1_vrijdag", level: "A1", topic: "Dies de la setmana", dutch: "vrijdag", catalan: "divendres",
    example: "Op vrijdag ga ik uit.", exampleTranslation: "El divendres surto." },
  { id: "a1_zaterdag", level: "A1", topic: "Dies de la setmana", dutch: "zaterdag", catalan: "dissabte" },
  { id: "a1_zondag", level: "A1", topic: "Dies de la setmana", dutch: "zondag", catalan: "diumenge",
    example: "Op zondag rust ik uit.", exampleTranslation: "El diumenge descanso." },

  // ── A1 · Mesos ───────────────────────────────────────────────────────────
  { id: "a1_januari", level: "A1", topic: "Mesos", dutch: "januari", catalan: "gener" },
  { id: "a1_februari", level: "A1", topic: "Mesos", dutch: "februari", catalan: "febrer" },
  { id: "a1_maart", level: "A1", topic: "Mesos", dutch: "maart", catalan: "març" },
  { id: "a1_april", level: "A1", topic: "Mesos", dutch: "april", catalan: "abril" },
  { id: "a1_mei", level: "A1", topic: "Mesos", dutch: "mei", catalan: "maig" },
  { id: "a1_juni", level: "A1", topic: "Mesos", dutch: "juni", catalan: "juny" },
  { id: "a1_juli", level: "A1", topic: "Mesos", dutch: "juli", catalan: "juliol" },
  { id: "a1_augustus", level: "A1", topic: "Mesos", dutch: "augustus", catalan: "agost" },
  { id: "a1_september", level: "A1", topic: "Mesos", dutch: "september", catalan: "setembre" },
  { id: "a1_oktober", level: "A1", topic: "Mesos", dutch: "oktober", catalan: "octubre" },
  { id: "a1_november", level: "A1", topic: "Mesos", dutch: "november", catalan: "novembre" },
  { id: "a1_december", level: "A1", topic: "Mesos", dutch: "december", catalan: "desembre" },

  // ── A1 · Colors ──────────────────────────────────────────────────────────
  { id: "a1_rood", level: "A1", topic: "Colors", dutch: "rood", catalan: "vermell",
    example: "De appel is rood.", exampleTranslation: "La poma és vermella." },
  { id: "a1_blauw", level: "A1", topic: "Colors", dutch: "blauw", catalan: "blau",
    example: "De lucht is blauw.", exampleTranslation: "El cel és blau." },
  { id: "a1_groen", level: "A1", topic: "Colors", dutch: "groen", catalan: "verd",
    example: "Het gras is groen.", exampleTranslation: "L'herba és verda." },
  { id: "a1_geel", level: "A1", topic: "Colors", dutch: "geel", catalan: "groc",
    example: "De zon is geel.", exampleTranslation: "El sol és groc." },
  { id: "a1_wit", level: "A1", topic: "Colors", dutch: "wit", catalan: "blanc",
    example: "De sneeuw is wit.", exampleTranslation: "La neu és blanca." },
  { id: "a1_zwart", level: "A1", topic: "Colors", dutch: "zwart", catalan: "negre",
    example: "De nacht is zwart.", exampleTranslation: "La nit és negra." },
  { id: "a1_oranje", level: "A1", topic: "Colors", dutch: "oranje", catalan: "taronja" },
  { id: "a1_paars", level: "A1", topic: "Colors", dutch: "paars", catalan: "morat" },
  { id: "a1_roze", level: "A1", topic: "Colors", dutch: "roze", catalan: "rosa" },
  { id: "a1_bruin", level: "A1", topic: "Colors", dutch: "bruin", catalan: "marró" },
  { id: "a1_grijs", level: "A1", topic: "Colors", dutch: "grijs", catalan: "gris" },

  // ── A1 · Família ─────────────────────────────────────────────────────────
  { id: "a1_vader", level: "A1", topic: "Família", dutch: "vader", catalan: "pare",
    example: "Mijn vader werkt thuis.", exampleTranslation: "El meu pare treballa a casa." },
  { id: "a1_moeder", level: "A1", topic: "Família", dutch: "moeder", catalan: "mare",
    example: "Mijn moeder kookt elke dag.", exampleTranslation: "La meva mare cuina cada dia." },
  { id: "a1_broer", level: "A1", topic: "Família", dutch: "broer", catalan: "germà",
    example: "Ik heb één broer.", exampleTranslation: "Tinc un germà." },
  { id: "a1_zus", level: "A1", topic: "Família", dutch: "zus", catalan: "germana",
    example: "Mijn zus is tien jaar oud.", exampleTranslation: "La meva germana té deu anys." },
  { id: "a1_opa", level: "A1", topic: "Família", dutch: "opa", catalan: "avi" },
  { id: "a1_oma", level: "A1", topic: "Família", dutch: "oma", catalan: "àvia" },
  { id: "a1_zoon", level: "A1", topic: "Família", dutch: "zoon", catalan: "fill" },
  { id: "a1_dochter", level: "A1", topic: "Família", dutch: "dochter", catalan: "filla" },
  { id: "a1_man", level: "A1", topic: "Família", dutch: "man", catalan: "home / marit" },
  { id: "a1_vrouw", level: "A1", topic: "Família", dutch: "vrouw", catalan: "dona / esposa" },
  { id: "a1_kind", level: "A1", topic: "Família", dutch: "kind", catalan: "nen / fill",
    example: "Het kind speelt in de tuin.", exampleTranslation: "El nen juga al jardí." },

  // ── A1 · Menjar i beguda ──────────────────────────────────────────────────
  { id: "a1_water", level: "A1", topic: "Menjar i beguda", dutch: "water", catalan: "aigua",
    example: "Ik drink water.", exampleTranslation: "Bec aigua." },
  { id: "a1_brood", level: "A1", topic: "Menjar i beguda", dutch: "brood", catalan: "pa",
    example: "Ik eet brood met kaas.", exampleTranslation: "Menjo pa amb formatge." },
  { id: "a1_kaas", level: "A1", topic: "Menjar i beguda", dutch: "kaas", catalan: "formatge" },
  { id: "a1_vlees", level: "A1", topic: "Menjar i beguda", dutch: "vlees", catalan: "carn" },
  { id: "a1_groente", level: "A1", topic: "Menjar i beguda", dutch: "groente", catalan: "verdura" },
  { id: "a1_fruit", level: "A1", topic: "Menjar i beguda", dutch: "fruit", catalan: "fruita",
    example: "Ik eet elke dag fruit.", exampleTranslation: "Menjo fruita cada dia." },
  { id: "a1_koffie", level: "A1", topic: "Menjar i beguda", dutch: "koffie", catalan: "cafè",
    example: "Wil je koffie?", exampleTranslation: "Vols cafè?" },
  { id: "a1_thee", level: "A1", topic: "Menjar i beguda", dutch: "thee", catalan: "te" },
  { id: "a1_bier", level: "A1", topic: "Menjar i beguda", dutch: "bier", catalan: "cervesa" },
  { id: "a1_melk", level: "A1", topic: "Menjar i beguda", dutch: "melk", catalan: "llet" },
  { id: "a1_appel", level: "A1", topic: "Menjar i beguda", dutch: "appel", catalan: "poma" },
  { id: "a1_ei", level: "A1", topic: "Menjar i beguda", dutch: "ei", catalan: "ou",
    example: "Ik eet een ei voor het ontbijt.", exampleTranslation: "Menjo un ou per esmorzar." },

  // ── A1 · Verbs bàsics ────────────────────────────────────────────────────
  { id: "a1_zijn", level: "A1", topic: "Verbs bàsics", dutch: "zijn", catalan: "ser / estar",
    example: "Ik ben student.", exampleTranslation: "Soc estudiant." },
  { id: "a1_hebben", level: "A1", topic: "Verbs bàsics", dutch: "hebben", catalan: "tenir",
    example: "Ik heb een hond.", exampleTranslation: "Tinc un gos." },
  { id: "a1_gaan", level: "A1", topic: "Verbs bàsics", dutch: "gaan", catalan: "anar",
    example: "Ik ga naar school.", exampleTranslation: "Vaig a l'escola." },
  { id: "a1_komen", level: "A1", topic: "Verbs bàsics", dutch: "komen", catalan: "venir",
    example: "Hij komt morgen.", exampleTranslation: "Ell ve demà." },
  { id: "a1_eten", level: "A1", topic: "Verbs bàsics", dutch: "eten", catalan: "menjar",
    example: "We eten om zes uur.", exampleTranslation: "Mengem a les sis." },
  { id: "a1_drinken", level: "A1", topic: "Verbs bàsics", dutch: "drinken", catalan: "beure",
    example: "Ik drink graag thee.", exampleTranslation: "M'agrada beure te." },
  { id: "a1_werken", level: "A1", topic: "Verbs bàsics", dutch: "werken", catalan: "treballar",
    example: "Zij werkt in Amsterdam.", exampleTranslation: "Ella treballa a Amsterdam." },
  { id: "a1_wonen", level: "A1", topic: "Verbs bàsics", dutch: "wonen", catalan: "viure / residir",
    example: "Ik woon in Barcelona.", exampleTranslation: "Visc a Barcelona." },
  { id: "a1_heten", level: "A1", topic: "Verbs bàsics", dutch: "heten", catalan: "dir-se (nom)",
    example: "Ik heet Anna.", exampleTranslation: "Em dic Anna." },
  { id: "a1_spreken", level: "A1", topic: "Verbs bàsics", dutch: "spreken", catalan: "parlar",
    example: "Ik spreek een beetje Nederlands.", exampleTranslation: "Parlo una mica de neerlandès." },
  { id: "a1_willen", level: "A1", topic: "Verbs bàsics", dutch: "willen", catalan: "voler",
    example: "Ik wil een koffie.", exampleTranslation: "Vull un cafè." },
  { id: "a1_kunnen", level: "A1", topic: "Verbs bàsics", dutch: "kunnen", catalan: "poder",
    example: "Kun jij Nederlands spreken?", exampleTranslation: "Pots parlar neerlandès?" },

  // ── A2 · Compres ─────────────────────────────────────────────────────────
  { id: "a2_winkel", level: "A2", topic: "Compres", dutch: "winkel", catalan: "botiga",
    example: "De winkel is om negen uur open.", exampleTranslation: "La botiga obre a les nou." },
  { id: "a2_kopen", level: "A2", topic: "Compres", dutch: "kopen", catalan: "comprar",
    example: "Ik wil dit jasje kopen.", exampleTranslation: "Vull comprar aquesta jaqueta." },
  { id: "a2_betalen", level: "A2", topic: "Compres", dutch: "betalen", catalan: "pagar",
    example: "Kan ik met kaart betalen?", exampleTranslation: "Puc pagar amb targeta?" },
  { id: "a2_prijs", level: "A2", topic: "Compres", dutch: "prijs", catalan: "preu",
    example: "Wat is de prijs?", exampleTranslation: "Quin és el preu?" },
  { id: "a2_goedkoop", level: "A2", topic: "Compres", dutch: "goedkoop", catalan: "barat",
    example: "Dit is heel goedkoop!", exampleTranslation: "Això és molt barat!" },
  { id: "a2_duur", level: "A2", topic: "Compres", dutch: "duur", catalan: "car",
    example: "Dit horloge is erg duur.", exampleTranslation: "Aquest rellotge és molt car." },
  { id: "a2_rekening", level: "A2", topic: "Compres", dutch: "rekening", catalan: "compte / factura",
    example: "De rekening, alsjeblieft.", exampleTranslation: "El compte, si us plau." },
  { id: "a2_kassabon", level: "A2", topic: "Compres", dutch: "kassabon", catalan: "tiquet / rebut" },
  { id: "a2_korting", level: "A2", topic: "Compres", dutch: "korting", catalan: "descompte",
    example: "Is er korting op dit product?", exampleTranslation: "Hi ha descompte en aquest producte?" },
  { id: "a2_maat", level: "A2", topic: "Compres", dutch: "maat", catalan: "talla / mida",
    example: "Welke maat heeft u?", exampleTranslation: "Quina talla té vostè?" },

  // ── A2 · Viatges i transport ─────────────────────────────────────────────
  { id: "a2_trein", level: "A2", topic: "Viatges i transport", dutch: "trein", catalan: "tren",
    example: "De trein vertrekt om tien uur.", exampleTranslation: "El tren surt a les deu." },
  { id: "a2_bus", level: "A2", topic: "Viatges i transport", dutch: "bus", catalan: "autobús",
    example: "Welke bus gaat naar het centrum?", exampleTranslation: "Quin autobús va al centre?" },
  { id: "a2_fiets", level: "A2", topic: "Viatges i transport", dutch: "fiets", catalan: "bicicleta",
    example: "Ik ga op de fiets naar werk.", exampleTranslation: "Vaig a treballar en bicicleta." },
  { id: "a2_auto", level: "A2", topic: "Viatges i transport", dutch: "auto", catalan: "cotxe",
    example: "Mijn auto is blauw.", exampleTranslation: "El meu cotxe és blau." },
  { id: "a2_station", level: "A2", topic: "Viatges i transport", dutch: "station", catalan: "estació",
    example: "Het station is hier vlakbij.", exampleTranslation: "L'estació és molt a prop." },
  { id: "a2_vliegtuig", level: "A2", topic: "Viatges i transport", dutch: "vliegtuig", catalan: "avió",
    example: "Het vliegtuig landt om vijf uur.", exampleTranslation: "L'avió aterra a les cinc." },
  { id: "a2_ticket", level: "A2", topic: "Viatges i transport", dutch: "ticket", catalan: "bitllet / entrada",
    example: "Ik heb een ticket voor Amsterdam.", exampleTranslation: "Tinc un bitllet per a Amsterdam." },
  { id: "a2_paspoort", level: "A2", topic: "Viatges i transport", dutch: "paspoort", catalan: "passaport",
    example: "Ik vergeet mijn paspoort bijna!", exampleTranslation: "Gairebé oblido el meu passaport!" },
  { id: "a2_reis", level: "A2", topic: "Viatges i transport", dutch: "reis", catalan: "viatge",
    example: "We gaan op reis naar Italië.", exampleTranslation: "Anem de viatge a Itàlia." },
  { id: "a2_kaart", level: "A2", topic: "Viatges i transport", dutch: "kaart", catalan: "mapa / targeta" },
  { id: "a2_links", level: "A2", topic: "Viatges i transport", dutch: "links", catalan: "a l'esquerra",
    example: "Sla links af bij het stoplicht.", exampleTranslation: "Gira a l'esquerra al semàfor." },
  { id: "a2_rechts", level: "A2", topic: "Viatges i transport", dutch: "rechts", catalan: "a la dreta",
    example: "Het hotel is rechts.", exampleTranslation: "L'hotel és a la dreta." },
  { id: "a2_rechtdoor", level: "A2", topic: "Viatges i transport", dutch: "rechtdoor", catalan: "tot recte",
    example: "Ga rechtdoor, dan zie je het.", exampleTranslation: "Ves tot recte i ho veuràs." },

  // ── A2 · Temps atmosfèric ─────────────────────────────────────────────────
  { id: "a2_warm", level: "A2", topic: "Temps atmosfèric", dutch: "warm", catalan: "calent / calorós",
    example: "Het is erg warm vandaag.", exampleTranslation: "Avui fa molta calor." },
  { id: "a2_koud", level: "A2", topic: "Temps atmosfèric", dutch: "koud", catalan: "fred",
    example: "Het is koud buiten.", exampleTranslation: "Fa fred a fora." },
  { id: "a2_regen", level: "A2", topic: "Temps atmosfèric", dutch: "regen", catalan: "pluja",
    example: "Er is veel regen in november.", exampleTranslation: "Al novembre plou molt." },
  { id: "a2_zon", level: "A2", topic: "Temps atmosfèric", dutch: "zon", catalan: "sol",
    example: "De zon schijnt vandaag.", exampleTranslation: "Avui brilla el sol." },
  { id: "a2_wind", level: "A2", topic: "Temps atmosfèric", dutch: "wind", catalan: "vent",
    example: "Er staat veel wind.", exampleTranslation: "Fa molt de vent." },
  { id: "a2_sneeuw", level: "A2", topic: "Temps atmosfèric", dutch: "sneeuw", catalan: "neu",
    example: "In de winter valt er sneeuw.", exampleTranslation: "A l'hivern cau neu." },
  { id: "a2_bewolkt", level: "A2", topic: "Temps atmosfèric", dutch: "bewolkt", catalan: "ennuvolat",
    example: "Het is bewolkt, maar droog.", exampleTranslation: "Està ennuvolat però sense pluja." },
  { id: "a2_temperatuur", level: "A2", topic: "Temps atmosfèric", dutch: "temperatuur", catalan: "temperatura",
    example: "De temperatuur is twaalf graden.", exampleTranslation: "La temperatura és de dotze graus." },
  { id: "a2_weer", level: "A2", topic: "Temps atmosfèric", dutch: "weer", catalan: "temps (meteorològic)",
    example: "Wat voor weer is het morgen?", exampleTranslation: "Quin temps farà demà?" },

  // ── A2 · Cos humà ─────────────────────────────────────────────────────────
  { id: "a2_hoofd", level: "A2", topic: "Cos humà", dutch: "hoofd", catalan: "cap",
    example: "Ik heb hoofdpijn.", exampleTranslation: "Tinc mal de cap." },
  { id: "a2_oog", level: "A2", topic: "Cos humà", dutch: "oog", catalan: "ull",
    example: "Ze heeft blauwe ogen.", exampleTranslation: "Ella té els ulls blaus." },
  { id: "a2_oor", level: "A2", topic: "Cos humà", dutch: "oor", catalan: "orella" },
  { id: "a2_neus", level: "A2", topic: "Cos humà", dutch: "neus", catalan: "nas" },
  { id: "a2_mond", level: "A2", topic: "Cos humà", dutch: "mond", catalan: "boca",
    example: "Open je mond, alsjeblieft.", exampleTranslation: "Obre la boca, si us plau." },
  { id: "a2_hand", level: "A2", topic: "Cos humà", dutch: "hand", catalan: "mà",
    example: "Geef me een hand.", exampleTranslation: "Dóna'm la mà." },
  { id: "a2_arm", level: "A2", topic: "Cos humà", dutch: "arm", catalan: "braç" },
  { id: "a2_been", level: "A2", topic: "Cos humà", dutch: "been", catalan: "cama" },
  { id: "a2_voet", level: "A2", topic: "Cos humà", dutch: "voet", catalan: "peu",
    example: "Mijn voet doet pijn.", exampleTranslation: "Em fa mal el peu." },
  { id: "a2_rug", level: "A2", topic: "Cos humà", dutch: "rug", catalan: "esquena",
    example: "Ik heb rugpijn.", exampleTranslation: "Tinc mal d'esquena." },
  { id: "a2_buik", level: "A2", topic: "Cos humà", dutch: "buik", catalan: "ventre / panxa",
    example: "Ik heb buikpijn.", exampleTranslation: "Tinc mal de panxa." },

  // ── A2 · Professions ─────────────────────────────────────────────────────
  { id: "a2_dokter", level: "A2", topic: "Professions", dutch: "dokter", catalan: "metge / metgessa",
    example: "Ik moet naar de dokter.", exampleTranslation: "He d'anar al metge." },
  { id: "a2_leraar", level: "A2", topic: "Professions", dutch: "leraar", catalan: "professor / mestre",
    example: "Mijn leraar spreekt drie talen.", exampleTranslation: "El meu professor parla tres idiomes." },
  { id: "a2_ingenieur", level: "A2", topic: "Professions", dutch: "ingenieur", catalan: "enginyer / enginyera" },
  { id: "a2_kok", level: "A2", topic: "Professions", dutch: "kok", catalan: "cuiner / cuinera",
    example: "De kok bereidt het eten.", exampleTranslation: "El cuiner prepara el menjar." },
  { id: "a2_chauffeur", level: "A2", topic: "Professions", dutch: "chauffeur", catalan: "conductor / xofer" },
  { id: "a2_verpleegkundige", level: "A2", topic: "Professions", dutch: "verpleegkundige", catalan: "infermer / infermera",
    example: "De verpleegkundige helpt de patiënt.", exampleTranslation: "L'infermer ajuda el pacient." },
  { id: "a2_architect", level: "A2", topic: "Professions", dutch: "architect", catalan: "arquitecte / arquitecta" },
  { id: "a2_advocaat", level: "A2", topic: "Professions", dutch: "advocaat", catalan: "advocat / advocada" },

  // ── A2 · Temps i adverbis ─────────────────────────────────────────────────
  { id: "a2_gisteren", level: "A2", topic: "Temps i adverbis", dutch: "gisteren", catalan: "ahir",
    example: "Gisteren was het mooi weer.", exampleTranslation: "Ahir feia bon temps." },
  { id: "a2_vandaag", level: "A2", topic: "Temps i adverbis", dutch: "vandaag", catalan: "avui",
    example: "Vandaag heb ik geen tijd.", exampleTranslation: "Avui no tinc temps." },
  { id: "a2_morgen", level: "A2", topic: "Temps i adverbis", dutch: "morgen", catalan: "demà",
    example: "Tot morgen!", exampleTranslation: "Fins demà!" },
  { id: "a2_nu", level: "A2", topic: "Temps i adverbis", dutch: "nu", catalan: "ara",
    example: "Ik ben nu thuis.", exampleTranslation: "Ara soc a casa." },
  { id: "a2_later", level: "A2", topic: "Temps i adverbis", dutch: "later", catalan: "més tard",
    example: "We spreken later.", exampleTranslation: "Parlem més tard." },
  { id: "a2_vroeg", level: "A2", topic: "Temps i adverbis", dutch: "vroeg", catalan: "d'hora",
    example: "Ik sta vroeg op.", exampleTranslation: "Em llevo d'hora." },
  { id: "a2_laat", level: "A2", topic: "Temps i adverbis", dutch: "laat", catalan: "tard",
    example: "Hij komt altijd te laat.", exampleTranslation: "Ell sempre arriba tard." },
  { id: "a2_snel", level: "A2", topic: "Temps i adverbis", dutch: "snel", catalan: "ràpid / de pressa",
    example: "Spreek niet zo snel!", exampleTranslation: "No parlis tan de pressa!" },
  { id: "a2_langzaam", level: "A2", topic: "Temps i adverbis", dutch: "langzaam", catalan: "lent / a poc a poc",
    example: "Kun je langzaam spreken?", exampleTranslation: "Pots parlar a poc a poc?" },

  // ── A2 · Aficions ────────────────────────────────────────────────────────
  { id: "a2_sporten", level: "A2", topic: "Aficions", dutch: "sporten", catalan: "fer esport",
    example: "Ik sport drie keer per week.", exampleTranslation: "Faig esport tres vegades per setmana." },
  { id: "a2_lezen", level: "A2", topic: "Aficions", dutch: "lezen", catalan: "llegir",
    example: "Ik lees graag romans.", exampleTranslation: "M'agrada llegir novel·les." },
  { id: "a2_muziek", level: "A2", topic: "Aficions", dutch: "muziek", catalan: "música",
    example: "Ik luister elke dag naar muziek.", exampleTranslation: "Escolto música cada dia." },
  { id: "a2_koken", level: "A2", topic: "Aficions", dutch: "koken", catalan: "cuinar",
    example: "Koken is mijn hobby.", exampleTranslation: "Cuinar és el meu hobby." },
  { id: "a2_reizen", level: "A2", topic: "Aficions", dutch: "reizen", catalan: "viatjar",
    example: "Ik hou van reizen.", exampleTranslation: "M'encanta viatjar." },
  { id: "a2_schilderen", level: "A2", topic: "Aficions", dutch: "schilderen", catalan: "pintar",
    example: "Ze schildert prachtige landschappen.", exampleTranslation: "Ella pinta paisatges preciosos." },
  { id: "a2_zwemmen", level: "A2", topic: "Aficions", dutch: "zwemmen", catalan: "nedar",
    example: "In de zomer zwem ik elke dag.", exampleTranslation: "A l'estiu nedo cada dia." },
  { id: "a2_fietsen", level: "A2", topic: "Aficions", dutch: "fietsen", catalan: "anar en bicicleta",
    example: "Nederlanders fietsen heel veel.", exampleTranslation: "Els neerlandesos van molt en bicicleta." },
  { id: "a2_dansen", level: "A2", topic: "Aficions", dutch: "dansen", catalan: "ballar",
    example: "Ik dans elke vrijdagavond.", exampleTranslation: "Ballo cada divendres al vespre." },
  { id: "a2_zingen", level: "A2", topic: "Aficions", dutch: "zingen", catalan: "cantar",
    example: "Ze zingt heel mooi.", exampleTranslation: "Ella canta molt bé." },

  // ── B1 · Opinions i emocions ──────────────────────────────────────────────
  { id: "b1_mening", level: "B1", topic: "Opinions i emocions", dutch: "mening", catalan: "opinió",
    example: "Wat is jouw mening hierover?", exampleTranslation: "Quina és la teva opinió sobre això?" },
  { id: "b1_denken", level: "B1", topic: "Opinions i emocions", dutch: "denken", catalan: "pensar / creure",
    example: "Ik denk dat hij gelijk heeft.", exampleTranslation: "Crec que té raó." },
  { id: "b1_begrijpen", level: "B1", topic: "Opinions i emocions", dutch: "begrijpen", catalan: "entendre / comprendre",
    example: "Ik begrijp je niet goed.", exampleTranslation: "No t'entenc bé." },
  { id: "b1_akkoord", level: "B1", topic: "Opinions i emocions", dutch: "akkoord gaan", catalan: "estar d'acord",
    example: "Ik ga niet akkoord met dit voorstel.", exampleTranslation: "No estic d'acord amb aquesta proposta." },
  { id: "b1_twijfelen", level: "B1", topic: "Opinions i emocions", dutch: "twijfelen", catalan: "dubtar",
    example: "Ik twijfel aan zijn intenties.", exampleTranslation: "Dubto de les seves intencions." },
  { id: "b1_teleurgesteld", level: "B1", topic: "Opinions i emocions", dutch: "teleurgesteld", catalan: "decebut / decebuda",
    example: "Ze was erg teleurgesteld.", exampleTranslation: "Ella estava molt decebuda." },
  { id: "b1_trots", level: "B1", topic: "Opinions i emocions", dutch: "trots", catalan: "orgullós / orgullosa",
    example: "Ik ben trots op jou!", exampleTranslation: "Estic orgullós de tu!" },
  { id: "b1_jaloers", level: "B1", topic: "Opinions i emocions", dutch: "jaloers", catalan: "gelós / gelosa",
    example: "Hij is jaloers op zijn broer.", exampleTranslation: "Ell és gelós del seu germà." },
  { id: "b1_zenuwachtig", level: "B1", topic: "Opinions i emocions", dutch: "zenuwachtig", catalan: "nerviós / nerviosa",
    example: "Ik ben zenuwachtig voor het examen.", exampleTranslation: "Estic nerviós per l'examen." },
  { id: "b1_opgelucht", level: "B1", topic: "Opinions i emocions", dutch: "opgelucht", catalan: "alleugerit / alleugerida",
    example: "Hij was opgelucht na het nieuws.", exampleTranslation: "Ell va quedar alleugerit després de la notícia." },

  // ── B1 · Feina i oficina ──────────────────────────────────────────────────
  { id: "b1_vergadering", level: "B1", topic: "Feina i oficina", dutch: "vergadering", catalan: "reunió",
    example: "De vergadering duurt twee uur.", exampleTranslation: "La reunió dura dues hores." },
  { id: "b1_solliciteren", level: "B1", topic: "Feina i oficina", dutch: "solliciteren", catalan: "sol·licitar (feina)",
    example: "Ik wil solliciteren naar deze baan.", exampleTranslation: "Vull sol·licitar aquesta feina." },
  { id: "b1_salaris", level: "B1", topic: "Feina i oficina", dutch: "salaris", catalan: "salari",
    example: "Mijn salaris is verhoogd.", exampleTranslation: "El meu salari ha augmentat." },
  { id: "b1_collega", level: "B1", topic: "Feina i oficina", dutch: "collega", catalan: "company de feina / col·lega",
    example: "Mijn collega helpt me altijd.", exampleTranslation: "El meu company de feina sempre m'ajuda." },
  { id: "b1_verslag", level: "B1", topic: "Feina i oficina", dutch: "verslag", catalan: "informe",
    example: "Ik schrijf een verslag voor mijn baas.", exampleTranslation: "Escric un informe per al meu cap." },
  { id: "b1_ontslaan", level: "B1", topic: "Feina i oficina", dutch: "ontslaan", catalan: "acomiadar",
    example: "Hij werd ontslagen na de crisis.", exampleTranslation: "Ell va ser acomiadat després de la crisi." },
  { id: "b1_bedrijf", level: "B1", topic: "Feina i oficina", dutch: "bedrijf", catalan: "empresa",
    example: "Ze werkt voor een groot bedrijf.", exampleTranslation: "Ella treballa per a una gran empresa." },

  // ── B1 · Salut i medicina ─────────────────────────────────────────────────
  { id: "b1_ziekenhuis", level: "B1", topic: "Salut i medicina", dutch: "ziekenhuis", catalan: "hospital",
    example: "Hij is opgenomen in het ziekenhuis.", exampleTranslation: "Ell ha estat ingressat a l'hospital." },
  { id: "b1_apotheek", level: "B1", topic: "Salut i medicina", dutch: "apotheek", catalan: "farmàcia",
    example: "Ik haal je medicijn op bij de apotheek.", exampleTranslation: "Recullo el teu medicament a la farmàcia." },
  { id: "b1_medicijn", level: "B1", topic: "Salut i medicina", dutch: "medicijn", catalan: "medicament",
    example: "Neem dit medicijn twee keer per dag.", exampleTranslation: "Pren aquest medicament dues vegades al dia." },
  { id: "b1_allergie", level: "B1", topic: "Salut i medicina", dutch: "allergie", catalan: "al·lèrgia",
    example: "Ze heeft een allergie voor pinda's.", exampleTranslation: "Ella té al·lèrgia als cacauets." },
  { id: "b1_recept", level: "B1", topic: "Salut i medicina", dutch: "recept", catalan: "recepta mèdica",
    example: "De dokter geeft me een recept.", exampleTranslation: "El metge em dona una recepta." },

  // ── B1 · Maatschappij / Societat ─────────────────────────────────────────
  { id: "b1_overheid", level: "B1", topic: "Societat", dutch: "overheid", catalan: "govern / administració pública",
    example: "De overheid moet actie ondernemen.", exampleTranslation: "El govern ha de prendre mesures." },
  { id: "b1_wet", level: "B1", topic: "Societat", dutch: "wet", catalan: "llei",
    example: "De wet verbiedt dit gedrag.", exampleTranslation: "La llei prohibeix aquest comportament." },
  { id: "b1_belasting", level: "B1", topic: "Societat", dutch: "belasting", catalan: "impost",
    example: "We betalen veel belasting.", exampleTranslation: "Paguem molts impostos." },
  { id: "b1_vrijheid", level: "B1", topic: "Societat", dutch: "vrijheid", catalan: "llibertat",
    example: "Vrijheid van meningsuiting is essentieel.", exampleTranslation: "La llibertat d'expressió és essencial." },
  { id: "b1_gelijkheid", level: "B1", topic: "Societat", dutch: "gelijkheid", catalan: "igualtat",
    example: "We strijden voor gelijkheid.", exampleTranslation: "Lluitem per la igualtat." },

  // ── B1 · Technologie ─────────────────────────────────────────────────────
  { id: "b1_wachtwoord", level: "B1", topic: "Technologie", dutch: "wachtwoord", catalan: "contrasenya",
    example: "Vergeet je wachtwoord niet!", exampleTranslation: "No oblidis la teva contrasenya!" },
  { id: "b1_scherm", level: "B1", topic: "Technologie", dutch: "scherm", catalan: "pantalla",
    example: "Het scherm is gebarsten.", exampleTranslation: "La pantalla s'ha trencat." },
  { id: "b1_opslaan", level: "B1", topic: "Technologie", dutch: "opslaan", catalan: "desar / guardar",
    example: "Sla je document op voor je sluit.", exampleTranslation: "Desa el document abans de tancar." },
  { id: "b1_draadloos", level: "B1", topic: "Technologie", dutch: "draadloos", catalan: "sense fils",
    example: "We hebben draadloos internet.", exampleTranslation: "Tenim internet sense fils." },

  // ── B2 · Conceptes abstractes ─────────────────────────────────────────────
  { id: "b2_verantwoordelijkheid", level: "B2", topic: "Conceptes abstractes", dutch: "verantwoordelijkheid", catalan: "responsabilitat",
    example: "Hij neemt zijn verantwoordelijkheid serieus.", exampleTranslation: "Ell pren la seva responsabilitat seriosament." },
  { id: "b2_gevolg", level: "B2", topic: "Conceptes abstractes", dutch: "gevolg", catalan: "conseqüència",
    example: "Dat kan ernstige gevolgen hebben.", exampleTranslation: "Això pot tenir greus conseqüències." },
  { id: "b2_oorzaak", level: "B2", topic: "Conceptes abstractes", dutch: "oorzaak", catalan: "causa",
    example: "Wat is de oorzaak van het probleem?", exampleTranslation: "Quina és la causa del problema?" },
  { id: "b2_invloed", level: "B2", topic: "Conceptes abstractes", dutch: "invloed", catalan: "influència",
    example: "Media heeft grote invloed op jongeren.", exampleTranslation: "Els mitjans de comunicació tenen molta influència sobre els joves." },
  { id: "b2_uitdaging", level: "B2", topic: "Conceptes abstractes", dutch: "uitdaging", catalan: "repte / desafiament",
    example: "Dit is een grote uitdaging voor ons.", exampleTranslation: "Això és un gran repte per a nosaltres." },
  { id: "b2_vooruitgang", level: "B2", topic: "Conceptes abstractes", dutch: "vooruitgang", catalan: "progrés",
    example: "Technologische vooruitgang gaat snel.", exampleTranslation: "El progrés tecnològic avança ràpidament." },
  { id: "b2_compromis", level: "B2", topic: "Conceptes abstractes", dutch: "compromis", catalan: "compromís",
    example: "Ze hebben een compromis bereikt.", exampleTranslation: "Han assolit un compromís." },
  { id: "b2_benadering", level: "B2", topic: "Conceptes abstractes", dutch: "benadering", catalan: "enfocament / perspectiva",
    example: "We moeten een andere benadering kiezen.", exampleTranslation: "Hem de triar un altre enfocament." },
  { id: "b2_bewustzijn", level: "B2", topic: "Conceptes abstractes", dutch: "bewustzijn", catalan: "consciència / conscienciació",
    example: "Er is meer bewustzijn nodig over dit thema.", exampleTranslation: "Cal més conscienciació sobre aquest tema." },

  // ── B2 · Negocis ──────────────────────────────────────────────────────────
  { id: "b2_markt", level: "B2", topic: "Negocis", dutch: "markt", catalan: "mercat",
    example: "De markt is erg concurrerend.", exampleTranslation: "El mercat és molt competitiu." },
  { id: "b2_concurrentie", level: "B2", topic: "Negocis", dutch: "concurrentie", catalan: "competència",
    example: "De concurrentie neemt toe.", exampleTranslation: "La competència augmenta." },
  { id: "b2_winst", level: "B2", topic: "Negocis", dutch: "winst", catalan: "benefici / guany",
    example: "Het bedrijf maakt veel winst.", exampleTranslation: "L'empresa obté molts beneficis." },
  { id: "b2_investering", level: "B2", topic: "Negocis", dutch: "investering", catalan: "inversió",
    example: "Dit vereist een grote investering.", exampleTranslation: "Això requereix una gran inversió." },
  { id: "b2_strategie", level: "B2", topic: "Negocis", dutch: "strategie", catalan: "estratègia",
    example: "We moeten onze strategie herzien.", exampleTranslation: "Hem de revisar la nostra estratègia." },
  { id: "b2_fusie", level: "B2", topic: "Negocis", dutch: "fusie", catalan: "fusió",
    example: "De fusie van beide bedrijven is rond.", exampleTranslation: "La fusió de les dues empreses s'ha tancat." },

  // ── B2 · Medi ambient ─────────────────────────────────────────────────────
  { id: "b2_klimaat", level: "B2", topic: "Medi ambient", dutch: "klimaat", catalan: "clima",
    example: "Het klimaat verandert snel.", exampleTranslation: "El clima canvia ràpidament." },
  { id: "b2_uitstoot", level: "B2", topic: "Medi ambient", dutch: "uitstoot", catalan: "emissions",
    example: "We moeten de uitstoot verminderen.", exampleTranslation: "Hem de reduir les emissions." },
  { id: "b2_hernieuwbaar", level: "B2", topic: "Medi ambient", dutch: "hernieuwbaar", catalan: "renovable",
    example: "Hernieuwbare energie is de toekomst.", exampleTranslation: "L'energia renovable és el futur." },
  { id: "b2_vervuiling", level: "B2", topic: "Medi ambient", dutch: "vervuiling", catalan: "contaminació",
    example: "Luchtvervuiling is een ernstig probleem.", exampleTranslation: "La contaminació de l'aire és un problema greu." },
  { id: "b2_duurzaam", level: "B2", topic: "Medi ambient", dutch: "duurzaam", catalan: "sostenible",
    example: "We kiezen voor duurzame producten.", exampleTranslation: "Triem productes sostenibles." },
  { id: "b2_biodiversiteit", level: "B2", topic: "Medi ambient", dutch: "biodiversiteit", catalan: "biodiversitat",
    example: "Biodiversiteit is cruciaal voor het ecosysteem.", exampleTranslation: "La biodiversitat és crucial per a l'ecosistema." },

  // ── B2 · Política ─────────────────────────────────────────────────────────
  { id: "b2_democratie", level: "B2", topic: "Política", dutch: "democratie", catalan: "democràcia",
    example: "Democratie vereist actieve burgers.", exampleTranslation: "La democràcia requereix ciutadans actius." },
  { id: "b2_verkiezing", level: "B2", topic: "Política", dutch: "verkiezing", catalan: "elecció / votació",
    example: "Er zijn morgen verkiezingen.", exampleTranslation: "Demà hi ha eleccions." },
  { id: "b2_grondwet", level: "B2", topic: "Política", dutch: "grondwet", catalan: "constitució",
    example: "De grondwet beschermt onze rechten.", exampleTranslation: "La constitució protegeix els nostres drets." },
  { id: "b2_beleid", level: "B2", topic: "Política", dutch: "beleid", catalan: "política / mesures",
    example: "Het nieuwe beleid is omstreden.", exampleTranslation: "La nova política és controvertida." },
  { id: "b2_parlement", level: "B2", topic: "Política", dutch: "parlement", catalan: "parlament",
    example: "Het parlement stemt over de wet.", exampleTranslation: "El parlament vota la llei." },

  // ── C1 · Llengua i retòrica ───────────────────────────────────────────────
  { id: "c1_metafoor", level: "C1", topic: "Llengua i retòrica", dutch: "metafoor", catalan: "metàfora",
    example: "De zin bevat een sterke metafoor.", exampleTranslation: "La frase conté una metàfora poderosa." },
  { id: "c1_ironie", level: "C1", topic: "Llengua i retòrica", dutch: "ironie", catalan: "ironia",
    example: "Zijn opmerking was doordrenkt van ironie.", exampleTranslation: "El seu comentari estava impregnat d'ironia." },
  { id: "c1_retorica", level: "C1", topic: "Llengua i retòrica", dutch: "retorica", catalan: "retòrica",
    example: "Zijn retorica was zeer overtuigend.", exampleTranslation: "La seva retòrica era molt convincent." },
  { id: "c1_nuanceren", level: "C1", topic: "Llengua i retòrica", dutch: "nuanceren", catalan: "matisar",
    example: "Je moet je standpunt meer nuanceren.", exampleTranslation: "Has de matisar més el teu punt de vista." },
  { id: "c1_betoog", level: "C1", topic: "Llengua i retòrica", dutch: "betoog", catalan: "argumentació / discurs",
    example: "Zijn betoog was logisch en helder.", exampleTranslation: "La seva argumentació era lògica i clara." },
  { id: "c1_woordspeling", level: "C1", topic: "Llengua i retòrica", dutch: "woordspeling", catalan: "joc de paraules",
    example: "De titel is een subtiele woordspeling.", exampleTranslation: "El títol és un subtil joc de paraules." },
  { id: "c1_stijlfiguur", level: "C1", topic: "Llengua i retòrica", dutch: "stijlfiguur", catalan: "figura retòrica",
    example: "Een vergelijking is een bekende stijlfiguur.", exampleTranslation: "La comparació és una figura retòrica coneguda." },

  // ── C1 · Dret i ètica ────────────────────────────────────────────────────
  { id: "c1_aansprakelijkheid", level: "C1", topic: "Dret i ètica", dutch: "aansprakelijkheid", catalan: "responsabilitat legal",
    example: "De aansprakelijkheid ligt bij de producent.", exampleTranslation: "La responsabilitat legal recau en el fabricant." },
  { id: "c1_vonnis", level: "C1", topic: "Dret i ètica", dutch: "vonnis", catalan: "sentència / veredicte",
    example: "Het vonnis was verrassend mild.", exampleTranslation: "La sentència va ser sorprenentment lleu." },
  { id: "c1_getuige", level: "C1", topic: "Dret i ètica", dutch: "getuige", catalan: "testimoni",
    example: "De getuige legde een verklaring af.", exampleTranslation: "El testimoni va fer una declaració." },
  { id: "c1_wetgeving", level: "C1", topic: "Dret i ètica", dutch: "wetgeving", catalan: "legislació",
    example: "De wetgeving moet worden aangepast.", exampleTranslation: "La legislació ha de ser adaptada." },
  { id: "c1_rechtbank", level: "C1", topic: "Dret i ètica", dutch: "rechtbank", catalan: "tribunal",
    example: "De zaak komt voor de rechtbank.", exampleTranslation: "El cas arriba al tribunal." },
  { id: "c1_vrijspraak", level: "C1", topic: "Dret i ètica", dutch: "vrijspraak", catalan: "absolució",
    example: "De rechter sprak hem vrij.", exampleTranslation: "El jutge el va absoldre." },

  // ── C1 · Filosofia ───────────────────────────────────────────────────────
  { id: "c1_vrije_wil", level: "C1", topic: "Filosofia", dutch: "vrije wil", catalan: "lliure albir",
    example: "Bestaat de vrije wil echt?", exampleTranslation: "Existeix realment el lliure albir?" },
  { id: "c1_ethiek", level: "C1", topic: "Filosofia", dutch: "ethiek", catalan: "ètica",
    example: "Ethiek bestudeert goed en kwaad.", exampleTranslation: "L'ètica estudia el bé i el mal." },
  { id: "c1_dialectiek", level: "C1", topic: "Filosofia", dutch: "dialectiek", catalan: "dialèctica",
    example: "Hegel ontwikkelde de dialectiek.", exampleTranslation: "Hegel va desenvolupar la dialèctica." },
  { id: "c1_subjectief", level: "C1", topic: "Filosofia", dutch: "subjectief", catalan: "subjectiu",
    example: "Schoonheid is subjectief.", exampleTranslation: "La bellesa és subjectiva." },
  { id: "c1_objectief", level: "C1", topic: "Filosofia", dutch: "objectief", catalan: "objectiu",
    example: "Probeer objectief te blijven.", exampleTranslation: "Intenta mantenir-te objectiu." },

  // ── C1 · Wetenschap / Ciència ─────────────────────────────────────────────
  { id: "c1_hypothese", level: "C1", topic: "Ciència", dutch: "hypothese", catalan: "hipòtesi",
    example: "De hypothese moet worden getest.", exampleTranslation: "La hipòtesi ha de ser comprovada." },
  { id: "c1_onderzoek", level: "C1", topic: "Ciència", dutch: "onderzoek", catalan: "recerca / investigació",
    example: "Het onderzoek duurt jaren.", exampleTranslation: "La recerca dura anys." },
  { id: "c1_paradigma", level: "C1", topic: "Ciència", dutch: "paradigma", catalan: "paradigma",
    example: "Dit ontdekking verandert het paradigma.", exampleTranslation: "Aquest descobriment canvia el paradigma." },
  { id: "c1_evolutie", level: "C1", topic: "Ciència", dutch: "evolutie", catalan: "evolució",
    example: "Evolutie is een wetenschappelijk feit.", exampleTranslation: "L'evolució és un fet científic." },
  { id: "c1_ecosysteem", level: "C1", topic: "Ciència", dutch: "ecosysteem", catalan: "ecosistema",
    example: "Het ecosysteem is fragiel.", exampleTranslation: "L'ecosistema és fràgil." },

  // ── C1 · Literatura ──────────────────────────────────────────────────────
  { id: "c1_allegorie", level: "C1", topic: "Literatura", dutch: "allegorie", catalan: "al·legoria",
    example: "De roman is een allegorie van de samenleving.", exampleTranslation: "La novel·la és una al·legoria de la societat." },
  { id: "c1_verteller", level: "C1", topic: "Literatura", dutch: "verteller", catalan: "narrador",
    example: "De verteller is onbetrouwbaar.", exampleTranslation: "El narrador no és de fiar." },
  { id: "c1_symboliek", level: "C1", topic: "Literatura", dutch: "symboliek", catalan: "simbolisme",
    example: "De symboliek in het gedicht is rijk.", exampleTranslation: "El simbolisme del poema és ric." },
  { id: "c1_plot", level: "C1", topic: "Literatura", dutch: "plot", catalan: "trama / argument",
    example: "Het plot heeft een onverwachte wending.", exampleTranslation: "La trama té un gir inesperat." },
  { id: "c1_proloog", level: "C1", topic: "Literatura", dutch: "proloog", catalan: "pròleg",
    example: "De proloog stelt het thema voor.", exampleTranslation: "El pròleg presenta el tema." },

];

// ── Dutch-German Flashcard Data ───────────────────────────────────────────────
// ~80 cards covering CEFR A1–C1 topics
// Card IDs prefixed with 'de_' to avoid collision with Dutch-Catalan IDs.
// 'example' = Dutch sentence, 'exampleTranslation' = German sentence.

const DE_CARDS = [

  // ── A1 · Grüße ───────────────────────────────────────────────────────────
  { id: "de_a1_hallo", level: "A1", topic: "Grüße", dutch: "hallo", german: "hallo",
    example: "Hallo, hoe gaat het?", exampleTranslation: "Hallo, wie geht es dir?" },
  { id: "de_a1_goedendag", level: "A1", topic: "Grüße", dutch: "goedendag", german: "guten Tag",
    example: "Goedendag, meneer.", exampleTranslation: "Guten Tag, mein Herr." },
  { id: "de_a1_goedemorgen", level: "A1", topic: "Grüße", dutch: "goedemorgen", german: "guten Morgen",
    example: "Goedemorgen! Heb je goed geslapen?", exampleTranslation: "Guten Morgen! Hast du gut geschlafen?" },
  { id: "de_a1_goedenavond", level: "A1", topic: "Grüße", dutch: "goedenavond", german: "guten Abend",
    example: "Goedenavond, welkom!", exampleTranslation: "Guten Abend, willkommen!" },
  { id: "de_a1_tot_ziens", level: "A1", topic: "Grüße", dutch: "tot ziens", german: "auf Wiedersehen",
    example: "Tot ziens, tot morgen!", exampleTranslation: "Auf Wiedersehen, bis morgen!" },
  { id: "de_a1_alsjeblieft", level: "A1", topic: "Grüße", dutch: "alsjeblieft", german: "bitte",
    example: "Een koffie, alsjeblieft.", exampleTranslation: "Einen Kaffee, bitte." },
  { id: "de_a1_dankjewel", level: "A1", topic: "Grüße", dutch: "dankjewel", german: "danke schön",
    example: "Dankjewel voor je hulp!", exampleTranslation: "Danke schön für deine Hilfe!" },
  { id: "de_a1_sorry", level: "A1", topic: "Grüße", dutch: "sorry / pardon", german: "Entschuldigung",
    example: "Sorry, ik begreep het niet.", exampleTranslation: "Entschuldigung, ich habe es nicht verstanden." },

  // ── A1 · Nummers ─────────────────────────────────────────────────────────
  { id: "de_a1_een", level: "A1", topic: "Nummers", dutch: "één", german: "eins" },
  { id: "de_a1_twee", level: "A1", topic: "Nummers", dutch: "twee", german: "zwei" },
  { id: "de_a1_drie", level: "A1", topic: "Nummers", dutch: "drie", german: "drei" },
  { id: "de_a1_vier", level: "A1", topic: "Nummers", dutch: "vier", german: "vier" },
  { id: "de_a1_vijf", level: "A1", topic: "Nummers", dutch: "vijf", german: "fünf" },
  { id: "de_a1_tien", level: "A1", topic: "Nummers", dutch: "tien", german: "zehn" },
  { id: "de_a1_honderd", level: "A1", topic: "Nummers", dutch: "honderd", german: "hundert" },

  // ── A1 · Dagen & Maanden ─────────────────────────────────────────────────
  { id: "de_a1_maandag", level: "A1", topic: "Dagen", dutch: "maandag", german: "Montag" },
  { id: "de_a1_dinsdag", level: "A1", topic: "Dagen", dutch: "dinsdag", german: "Dienstag" },
  { id: "de_a1_woensdag", level: "A1", topic: "Dagen", dutch: "woensdag", german: "Mittwoch" },
  { id: "de_a1_donderdag", level: "A1", topic: "Dagen", dutch: "donderdag", german: "Donnerstag" },
  { id: "de_a1_vrijdag", level: "A1", topic: "Dagen", dutch: "vrijdag", german: "Freitag" },
  { id: "de_a1_zaterdag", level: "A1", topic: "Dagen", dutch: "zaterdag", german: "Samstag" },
  { id: "de_a1_zondag", level: "A1", topic: "Dagen", dutch: "zondag", german: "Sonntag" },
  { id: "de_a1_januari", level: "A1", topic: "Maanden", dutch: "januari", german: "Januar" },
  { id: "de_a1_februari", level: "A1", topic: "Maanden", dutch: "februari", german: "Februar" },
  { id: "de_a1_maart", level: "A1", topic: "Maanden", dutch: "maart", german: "März" },

  // ── A1 · Familie ─────────────────────────────────────────────────────────
  { id: "de_a1_vader", level: "A1", topic: "Familie", dutch: "vader", german: "Vater",
    example: "Mijn vader werkt in Amsterdam.", exampleTranslation: "Mein Vater arbeitet in Amsterdam." },
  { id: "de_a1_moeder", level: "A1", topic: "Familie", dutch: "moeder", german: "Mutter",
    example: "Mijn moeder kookt elke dag.", exampleTranslation: "Meine Mutter kocht jeden Tag." },
  { id: "de_a1_broer", level: "A1", topic: "Familie", dutch: "broer", german: "Bruder" },
  { id: "de_a1_zus", level: "A1", topic: "Familie", dutch: "zus", german: "Schwester" },
  { id: "de_a1_kind", level: "A1", topic: "Familie", dutch: "kind", german: "Kind" },

  // ── A1 · Eten & Drinken ──────────────────────────────────────────────────
  { id: "de_a1_water", level: "A1", topic: "Eten", dutch: "water", german: "Wasser",
    example: "Mag ik een glas water?", exampleTranslation: "Darf ich ein Glas Wasser haben?" },
  { id: "de_a1_brood", level: "A1", topic: "Eten", dutch: "brood", german: "Brot",
    example: "Ik eet elke ochtend brood.", exampleTranslation: "Ich esse jeden Morgen Brot." },
  { id: "de_a1_melk", level: "A1", topic: "Eten", dutch: "melk", german: "Milch" },
  { id: "de_a1_koffie", level: "A1", topic: "Eten", dutch: "koffie", german: "Kaffee" },
  { id: "de_a1_appel", level: "A1", topic: "Eten", dutch: "appel", german: "Apfel" },

  // ── A2 · Werkwoorden ─────────────────────────────────────────────────────
  { id: "de_a2_werken", level: "A2", topic: "Werkwoorden", dutch: "werken", german: "arbeiten",
    example: "Ik werk elke dag.", exampleTranslation: "Ich arbeite jeden Tag." },
  { id: "de_a2_wonen", level: "A2", topic: "Werkwoorden", dutch: "wonen", german: "wohnen",
    example: "Ik woon in Rotterdam.", exampleTranslation: "Ich wohne in Rotterdam." },
  { id: "de_a2_spreken", level: "A2", topic: "Werkwoorden", dutch: "spreken", german: "sprechen",
    example: "Spreek je Duits?", exampleTranslation: "Sprichst du Deutsch?" },
  { id: "de_a2_eten", level: "A2", topic: "Werkwoorden", dutch: "eten", german: "essen",
    example: "Wat wil je eten?", exampleTranslation: "Was möchtest du essen?" },
  { id: "de_a2_drinken", level: "A2", topic: "Werkwoorden", dutch: "drinken", german: "trinken",
    example: "Wil je iets drinken?", exampleTranslation: "Möchtest du etwas trinken?" },
  { id: "de_a2_gaan", level: "A2", topic: "Werkwoorden", dutch: "gaan", german: "gehen",
    example: "Ik ga naar school.", exampleTranslation: "Ich gehe zur Schule." },
  { id: "de_a2_komen", level: "A2", topic: "Werkwoorden", dutch: "komen", german: "kommen",
    example: "Wanneer kom je thuis?", exampleTranslation: "Wann kommst du nach Hause?" },
  { id: "de_a2_kopen", level: "A2", topic: "Werkwoorden", dutch: "kopen", german: "kaufen",
    example: "Ik wil een boek kopen.", exampleTranslation: "Ich möchte ein Buch kaufen." },

  // ── A2 · Kleuren ─────────────────────────────────────────────────────────
  { id: "de_a2_rood", level: "A2", topic: "Kleuren", dutch: "rood", german: "rot" },
  { id: "de_a2_blauw", level: "A2", topic: "Kleuren", dutch: "blauw", german: "blau" },
  { id: "de_a2_groen", level: "A2", topic: "Kleuren", dutch: "groen", german: "grün" },
  { id: "de_a2_geel", level: "A2", topic: "Kleuren", dutch: "geel", german: "gelb" },
  { id: "de_a2_zwart", level: "A2", topic: "Kleuren", dutch: "zwart", german: "schwarz" },
  { id: "de_a2_wit", level: "A2", topic: "Kleuren", dutch: "wit", german: "weiß" },

  // ── A2 · Weer ────────────────────────────────────────────────────────────
  { id: "de_a2_regen", level: "A2", topic: "Weer", dutch: "regen", german: "Regen",
    example: "Het regent vandaag.", exampleTranslation: "Es regnet heute." },
  { id: "de_a2_zon", level: "A2", topic: "Weer", dutch: "zon", german: "Sonne",
    example: "De zon schijnt.", exampleTranslation: "Die Sonne scheint." },
  { id: "de_a2_sneeuw", level: "A2", topic: "Weer", dutch: "sneeuw", german: "Schnee" },
  { id: "de_a2_wind", level: "A2", topic: "Weer", dutch: "wind", german: "Wind" },
  { id: "de_a2_warm", level: "A2", topic: "Weer", dutch: "warm", german: "warm" },
  { id: "de_a2_koud", level: "A2", topic: "Weer", dutch: "koud", german: "kalt" },

  // ── B1 · Reizen ──────────────────────────────────────────────────────────
  { id: "de_b1_trein", level: "B1", topic: "Reizen", dutch: "trein", german: "Zug",
    example: "De trein vertrekt om tien uur.", exampleTranslation: "Der Zug fährt um zehn Uhr ab." },
  { id: "de_b1_vliegtuig", level: "B1", topic: "Reizen", dutch: "vliegtuig", german: "Flugzeug",
    example: "Het vliegtuig landt in Amsterdam.", exampleTranslation: "Das Flugzeug landet in Amsterdam." },
  { id: "de_b1_paspoort", level: "B1", topic: "Reizen", dutch: "paspoort", german: "Reisepass",
    example: "Vergeet je paspoort niet!", exampleTranslation: "Vergiss deinen Reisepass nicht!" },
  { id: "de_b1_hotel", level: "B1", topic: "Reizen", dutch: "hotel", german: "Hotel",
    example: "We verblijven in een hotel.", exampleTranslation: "Wir übernachten in einem Hotel." },
  { id: "de_b1_grens", level: "B1", topic: "Reizen", dutch: "grens", german: "Grenze",
    example: "We rijden over de grens.", exampleTranslation: "Wir fahren über die Grenze." },

  // ── B1 · Werk & Kantoor ──────────────────────────────────────────────────
  { id: "de_b1_vergadering", level: "B1", topic: "Werk", dutch: "vergadering", german: "Besprechung / Meeting",
    example: "De vergadering begint om negen uur.", exampleTranslation: "Die Besprechung beginnt um neun Uhr." },
  { id: "de_b1_collega", level: "B1", topic: "Werk", dutch: "collega", german: "Kollege / Kollegin",
    example: "Mijn collega is erg vriendelijk.", exampleTranslation: "Mein Kollege ist sehr freundlich." },
  { id: "de_b1_contract", level: "B1", topic: "Werk", dutch: "contract", german: "Vertrag",
    example: "Hij heeft een nieuw contract getekend.", exampleTranslation: "Er hat einen neuen Vertrag unterschrieben." },
  { id: "de_b1_salaris", level: "B1", topic: "Werk", dutch: "salaris", german: "Gehalt",
    example: "Ze heeft een goed salaris.", exampleTranslation: "Sie hat ein gutes Gehalt." },

  // ── B1 · Gezondheid ──────────────────────────────────────────────────────
  { id: "de_b1_dokter", level: "B1", topic: "Gezondheid", dutch: "dokter", german: "Arzt / Ärztin",
    example: "Ik ga naar de dokter.", exampleTranslation: "Ich gehe zum Arzt." },
  { id: "de_b1_ziekenhuis", level: "B1", topic: "Gezondheid", dutch: "ziekenhuis", german: "Krankenhaus",
    example: "Hij ligt in het ziekenhuis.", exampleTranslation: "Er liegt im Krankenhaus." },
  { id: "de_b1_pijn", level: "B1", topic: "Gezondheid", dutch: "pijn", german: "Schmerz",
    example: "Ik heb pijn in mijn rug.", exampleTranslation: "Ich habe Schmerzen im Rücken." },
  { id: "de_b1_medicijn", level: "B1", topic: "Gezondheid", dutch: "medicijn", german: "Medikament",
    example: "Neemt u dit medicijn tweemaal per dag.", exampleTranslation: "Nehmen Sie dieses Medikament zweimal täglich." },

  // ── B2 · Samenleving ─────────────────────────────────────────────────────
  { id: "de_b2_democratie", level: "B2", topic: "Samenleving", dutch: "democratie", german: "Demokratie",
    example: "Democratie vereist actieve deelname.", exampleTranslation: "Demokratie erfordert aktive Teilnahme." },
  { id: "de_b2_vrijheid", level: "B2", topic: "Samenleving", dutch: "vrijheid", german: "Freiheit",
    example: "Vrijheid van meningsuiting is essentieel.", exampleTranslation: "Meinungsfreiheit ist wesentlich." },
  { id: "de_b2_gelijkheid", level: "B2", topic: "Samenleving", dutch: "gelijkheid", german: "Gleichheit",
    example: "Ze strijden voor gelijkheid.", exampleTranslation: "Sie kämpfen für Gleichheit." },
  { id: "de_b2_duurzaamheid", level: "B2", topic: "Milieu", dutch: "duurzaamheid", german: "Nachhaltigkeit",
    example: "Duurzaamheid is de uitdaging van onze tijd.", exampleTranslation: "Nachhaltigkeit ist die Herausforderung unserer Zeit." },
  { id: "de_b2_klimaat", level: "B2", topic: "Milieu", dutch: "klimaat", german: "Klima",
    example: "Het klimaat verandert snel.", exampleTranslation: "Das Klima verändert sich schnell." },
  { id: "de_b2_economie", level: "B2", topic: "Economie", dutch: "economie", german: "Wirtschaft",
    example: "De economie groeit dit jaar.", exampleTranslation: "Die Wirtschaft wächst dieses Jahr." },
  { id: "de_b2_beleid", level: "B2", topic: "Politiek", dutch: "beleid", german: "Politik / Richtlinie",
    example: "De regering voert een nieuw beleid in.", exampleTranslation: "Die Regierung führt eine neue Politik ein." },

  // ── C1 · Abstracte concepten ─────────────────────────────────────────────
  { id: "de_c1_bewustzijn", level: "C1", topic: "Filosofie", dutch: "bewustzijn", german: "Bewusstsein",
    example: "Bewustzijn is een complex fenomeen.", exampleTranslation: "Bewusstsein ist ein komplexes Phänomen." },
  { id: "de_c1_paradox", level: "C1", topic: "Filosofie", dutch: "paradox", german: "Paradox",
    example: "Dat is een interessante paradox.", exampleTranslation: "Das ist ein interessantes Paradox." },
  { id: "de_c1_ethiek", level: "C1", topic: "Filosofie", dutch: "ethiek", german: "Ethik",
    example: "Ethiek stuurt ons handelen.", exampleTranslation: "Ethik leitet unser Handeln." },
  { id: "de_c1_retorica", level: "C1", topic: "Taal", dutch: "retorica", german: "Rhetorik",
    example: "Zijn retorica was overtuigend.", exampleTranslation: "Seine Rhetorik war überzeugend." },
  { id: "de_c1_nuance", level: "C1", topic: "Taal", dutch: "nuance", german: "Nuance",
    example: "De nuance is hier belangrijk.", exampleTranslation: "Die Nuance ist hier wichtig." },
  { id: "de_c1_integriteit", level: "C1", topic: "Maatschappij", dutch: "integriteit", german: "Integrität",
    example: "Integriteit is de basis van vertrouwen.", exampleTranslation: "Integrität ist die Grundlage des Vertrauens." },

  // ═══════════════════════════════════════════════════════════════════════════
  // PARITY ADDITIONS — brings DE_CARDS to 250 to match CARDS (Dutch-Catalan)
  // ═══════════════════════════════════════════════════════════════════════════

  // ── A1 · Grüße (extras) ──────────────────────────────────────────────────
  { id: "de_a1_prettig", level: "A1", topic: "Grüße", dutch: "prettig kennis te maken", german: "schön, Sie kennenzulernen",
    example: "Prettig kennis te maken!", exampleTranslation: "Schön, Sie kennenzulernen!" },
  { id: "de_a1_tot_morgen", level: "A1", topic: "Grüße", dutch: "tot morgen", german: "bis morgen",
    example: "Tot morgen! Slaap lekker.", exampleTranslation: "Bis morgen! Schlaf gut." },

  // ── A1 · Nummers (6–20 + large) ──────────────────────────────────────────
  { id: "de_a1_nul",      level: "A1", topic: "Nummers", dutch: "nul",      german: "null" },
  { id: "de_a1_zes",      level: "A1", topic: "Nummers", dutch: "zes",      german: "sechs" },
  { id: "de_a1_zeven",    level: "A1", topic: "Nummers", dutch: "zeven",    german: "sieben" },
  { id: "de_a1_acht",     level: "A1", topic: "Nummers", dutch: "acht",     german: "acht" },
  { id: "de_a1_negen",    level: "A1", topic: "Nummers", dutch: "negen",    german: "neun" },
  { id: "de_a1_elf",      level: "A1", topic: "Nummers", dutch: "elf",      german: "elf" },
  { id: "de_a1_twaalf",   level: "A1", topic: "Nummers", dutch: "twaalf",   german: "zwölf" },
  { id: "de_a1_dertien",  level: "A1", topic: "Nummers", dutch: "dertien",  german: "dreizehn" },
  { id: "de_a1_veertien", level: "A1", topic: "Nummers", dutch: "veertien", german: "vierzehn" },
  { id: "de_a1_vijftien", level: "A1", topic: "Nummers", dutch: "vijftien", german: "fünfzehn" },
  { id: "de_a1_twintig",  level: "A1", topic: "Nummers", dutch: "twintig",  german: "zwanzig" },
  { id: "de_a1_dertig",   level: "A1", topic: "Nummers", dutch: "dertig",   german: "dreißig" },
  { id: "de_a1_duizend",  level: "A1", topic: "Nummers", dutch: "duizend",  german: "tausend" },

  // ── A1 · Maanden (April–December) ────────────────────────────────────────
  { id: "de_a1_april",     level: "A1", topic: "Maanden", dutch: "april",     german: "April" },
  { id: "de_a1_mei",       level: "A1", topic: "Maanden", dutch: "mei",       german: "Mai" },
  { id: "de_a1_juni",      level: "A1", topic: "Maanden", dutch: "juni",      german: "Juni" },
  { id: "de_a1_juli",      level: "A1", topic: "Maanden", dutch: "juli",      german: "Juli" },
  { id: "de_a1_augustus",  level: "A1", topic: "Maanden", dutch: "augustus",  german: "August" },
  { id: "de_a1_september", level: "A1", topic: "Maanden", dutch: "september", german: "September" },
  { id: "de_a1_oktober",   level: "A1", topic: "Maanden", dutch: "oktober",   german: "Oktober" },
  { id: "de_a1_november",  level: "A1", topic: "Maanden", dutch: "november",  german: "November" },
  { id: "de_a1_december",  level: "A1", topic: "Maanden", dutch: "december",  german: "Dezember" },

  // ── A1 · Eten (extra food & drink) ───────────────────────────────────────
  { id: "de_a1_thee",    level: "A1", topic: "Eten", dutch: "thee",    german: "Tee",
    example: "Wil je een kopje thee?", exampleTranslation: "Möchtest du eine Tasse Tee?" },
  { id: "de_a1_vlees",   level: "A1", topic: "Eten", dutch: "vlees",   german: "Fleisch" },
  { id: "de_a1_vis",     level: "A1", topic: "Eten", dutch: "vis",     german: "Fisch" },
  { id: "de_a1_kaas",    level: "A1", topic: "Eten", dutch: "kaas",    german: "Käse" },
  { id: "de_a1_ei",      level: "A1", topic: "Eten", dutch: "ei",      german: "Ei" },
  { id: "de_a1_groente", level: "A1", topic: "Eten", dutch: "groente", german: "Gemüse" },
  { id: "de_a1_fruit",   level: "A1", topic: "Eten", dutch: "fruit",   german: "Obst" },

  // ── A1 · Familie (extended) ───────────────────────────────────────────────
  { id: "de_a1_opa",   level: "A1", topic: "Familie", dutch: "opa",   german: "Opa / Großvater" },
  { id: "de_a1_oma",   level: "A1", topic: "Familie", dutch: "oma",   german: "Oma / Großmutter" },
  { id: "de_a1_oom",   level: "A1", topic: "Familie", dutch: "oom",   german: "Onkel" },
  { id: "de_a1_tante", level: "A1", topic: "Familie", dutch: "tante", german: "Tante" },
  { id: "de_a1_neef",  level: "A1", topic: "Familie", dutch: "neef",  german: "Cousin / Neffe" },
  { id: "de_a1_nicht", level: "A1", topic: "Familie", dutch: "nicht", german: "Cousine / Nichte" },

  // ── A1 · Basiszinnen (basic verbs) ───────────────────────────────────────
  { id: "de_a1_zijn",     level: "A1", topic: "Basiszinnen", dutch: "zijn",     german: "sein",
    example: "Ik ben student.", exampleTranslation: "Ich bin Student." },
  { id: "de_a1_hebben",   level: "A1", topic: "Basiszinnen", dutch: "hebben",   german: "haben",
    example: "Ik heb een vraag.", exampleTranslation: "Ich habe eine Frage." },
  { id: "de_a1_willen",   level: "A1", topic: "Basiszinnen", dutch: "willen",   german: "wollen",
    example: "Ik wil een koffie.", exampleTranslation: "Ich will einen Kaffee." },
  { id: "de_a1_kunnen",   level: "A1", topic: "Basiszinnen", dutch: "kunnen",   german: "können",
    example: "Kun je zwemmen?", exampleTranslation: "Kannst du schwimmen?" },
  { id: "de_a1_moeten",   level: "A1", topic: "Basiszinnen", dutch: "moeten",   german: "müssen",
    example: "Ik moet nu gaan.", exampleTranslation: "Ich muss jetzt gehen." },
  { id: "de_a1_mogen",    level: "A1", topic: "Basiszinnen", dutch: "mogen",    german: "dürfen",
    example: "Mag ik binnenkomen?", exampleTranslation: "Darf ich hereinkommen?" },
  { id: "de_a1_zien",     level: "A1", topic: "Basiszinnen", dutch: "zien",     german: "sehen",
    example: "Ik zie een vogel.", exampleTranslation: "Ich sehe einen Vogel." },
  { id: "de_a1_horen",    level: "A1", topic: "Basiszinnen", dutch: "horen",    german: "hören",
    example: "Ik hoor muziek.", exampleTranslation: "Ich höre Musik." },
  { id: "de_a1_weten",    level: "A1", topic: "Basiszinnen", dutch: "weten",    german: "wissen",
    example: "Weet jij het antwoord?", exampleTranslation: "Weißt du die Antwort?" },
  { id: "de_a1_denken",   level: "A1", topic: "Basiszinnen", dutch: "denken",   german: "denken",
    example: "Ik denk dat je gelijk hebt.", exampleTranslation: "Ich denke, du hast recht." },
  { id: "de_a1_zeggen",   level: "A1", topic: "Basiszinnen", dutch: "zeggen",   german: "sagen",
    example: "Wat wil je zeggen?", exampleTranslation: "Was willst du sagen?" },
  { id: "de_a1_beginnen", level: "A1", topic: "Basiszinnen", dutch: "beginnen", german: "anfangen / beginnen",
    example: "We beginnen om acht uur.", exampleTranslation: "Wir fangen um acht Uhr an." },

  // ── A1 · Bijvoeglijke naamwoorden (basic adjectives) ─────────────────────
  { id: "de_a1_groot",      level: "A1", topic: "Bijvoeglijke naamwoorden", dutch: "groot",      german: "groß" },
  { id: "de_a1_klein",      level: "A1", topic: "Bijvoeglijke naamwoorden", dutch: "klein",      german: "klein" },
  { id: "de_a1_goed",       level: "A1", topic: "Bijvoeglijke naamwoorden", dutch: "goed",       german: "gut",
    example: "Het eten is goed.", exampleTranslation: "Das Essen ist gut." },
  { id: "de_a1_slecht",     level: "A1", topic: "Bijvoeglijke naamwoorden", dutch: "slecht",     german: "schlecht" },
  { id: "de_a1_mooi",       level: "A1", topic: "Bijvoeglijke naamwoorden", dutch: "mooi",       german: "schön",
    example: "Wat een mooie dag!", exampleTranslation: "Was für ein schöner Tag!" },
  { id: "de_a1_nieuw",      level: "A1", topic: "Bijvoeglijke naamwoorden", dutch: "nieuw",      german: "neu" },
  { id: "de_a1_oud",        level: "A1", topic: "Bijvoeglijke naamwoorden", dutch: "oud",        german: "alt" },
  { id: "de_a1_snel",       level: "A1", topic: "Bijvoeglijke naamwoorden", dutch: "snel",       german: "schnell" },
  { id: "de_a1_langzaam",   level: "A1", topic: "Bijvoeglijke naamwoorden", dutch: "langzaam",   german: "langsam" },
  { id: "de_a1_duur",       level: "A1", topic: "Bijvoeglijke naamwoorden", dutch: "duur",       german: "teuer" },
  { id: "de_a1_goedkoop",   level: "A1", topic: "Bijvoeglijke naamwoorden", dutch: "goedkoop",   german: "günstig / billig" },

  // ── A2 · Reizen ───────────────────────────────────────────────────────────
  { id: "de_a2_fiets",    level: "A2", topic: "Reizen", dutch: "fiets",    german: "Fahrrad",
    example: "Ik ga met de fiets naar school.", exampleTranslation: "Ich fahre mit dem Fahrrad zur Schule." },
  { id: "de_a2_auto",     level: "A2", topic: "Reizen", dutch: "auto",     german: "Auto",
    example: "Hij rijdt elke dag met de auto.", exampleTranslation: "Er fährt jeden Tag mit dem Auto." },
  { id: "de_a2_bus",      level: "A2", topic: "Reizen", dutch: "bus",      german: "Bus",
    example: "De bus komt over vijf minuten.", exampleTranslation: "Der Bus kommt in fünf Minuten." },
  { id: "de_a2_metro",    level: "A2", topic: "Reizen", dutch: "metro",    german: "U-Bahn",
    example: "We nemen de metro naar het centrum.", exampleTranslation: "Wir nehmen die U-Bahn zur Innenstadt." },
  { id: "de_a2_taxi",     level: "A2", topic: "Reizen", dutch: "taxi",     german: "Taxi" },
  { id: "de_a2_boot",     level: "A2", topic: "Reizen", dutch: "boot",     german: "Boot / Schiff" },
  { id: "de_a2_kaartje",  level: "A2", topic: "Reizen", dutch: "kaartje",  german: "Fahrkarte / Ticket",
    example: "Ik koop een kaartje voor de trein.", exampleTranslation: "Ich kaufe eine Fahrkarte für den Zug." },
  { id: "de_a2_koffer",   level: "A2", topic: "Reizen", dutch: "koffer",   german: "Koffer",
    example: "Mijn koffer is te zwaar.", exampleTranslation: "Mein Koffer ist zu schwer." },
  { id: "de_a2_aankomst", level: "A2", topic: "Reizen", dutch: "aankomst", german: "Ankunft",
    example: "De aankomst is om tien uur.", exampleTranslation: "Die Ankunft ist um zehn Uhr." },
  { id: "de_a2_vertrek",  level: "A2", topic: "Reizen", dutch: "vertrek",  german: "Abfahrt / Abreise",
    example: "Het vertrek is om negen uur.", exampleTranslation: "Die Abfahrt ist um neun Uhr." },
  { id: "de_a2_halte",    level: "A2", topic: "Reizen", dutch: "halte",    german: "Haltestelle" },
  { id: "de_a2_station",  level: "A2", topic: "Reizen", dutch: "station",  german: "Bahnhof",
    example: "Waar is het station?", exampleTranslation: "Wo ist der Bahnhof?" },
  { id: "de_a2_weg",      level: "A2", topic: "Reizen", dutch: "weg",      german: "Weg / Straße",
    example: "Dit is de verkeerde weg.", exampleTranslation: "Das ist der falsche Weg." },

  // ── A2 · Winkelen ─────────────────────────────────────────────────────────
  { id: "de_a2_winkel",      level: "A2", topic: "Winkelen", dutch: "winkel",      german: "Laden / Geschäft",
    example: "De winkel is om tien uur open.", exampleTranslation: "Der Laden öffnet um zehn Uhr." },
  { id: "de_a2_supermarkt",  level: "A2", topic: "Winkelen", dutch: "supermarkt",  german: "Supermarkt" },
  { id: "de_a2_prijs",       level: "A2", topic: "Winkelen", dutch: "prijs",       german: "Preis",
    example: "Wat is de prijs?", exampleTranslation: "Was ist der Preis?" },
  { id: "de_a2_kassa",       level: "A2", topic: "Winkelen", dutch: "kassa",       german: "Kasse" },
  { id: "de_a2_betalen",     level: "A2", topic: "Winkelen", dutch: "betalen",     german: "bezahlen",
    example: "Hoe wil je betalen?", exampleTranslation: "Wie möchtest du bezahlen?" },
  { id: "de_a2_korting",     level: "A2", topic: "Winkelen", dutch: "korting",     german: "Rabatt / Ermäßigung",
    example: "Er is tien procent korting.", exampleTranslation: "Es gibt zehn Prozent Rabatt." },
  { id: "de_a2_rekening",    level: "A2", topic: "Winkelen", dutch: "rekening",    german: "Rechnung",
    example: "Mag ik de rekening?", exampleTranslation: "Darf ich die Rechnung haben?" },
  { id: "de_a2_geld",        level: "A2", topic: "Winkelen", dutch: "geld",        german: "Geld" },
  { id: "de_a2_creditcard",  level: "A2", topic: "Winkelen", dutch: "creditcard",  german: "Kreditkarte" },
  { id: "de_a2_passen",      level: "A2", topic: "Winkelen", dutch: "passen",      german: "anprobieren",
    example: "Mag ik dit passen?", exampleTranslation: "Darf ich das anprobieren?" },

  // ── A2 · Hobby's ──────────────────────────────────────────────────────────
  { id: "de_a2_lezen",          level: "A2", topic: "Hobby's", dutch: "lezen",          german: "lesen",
    example: "Ik lees graag boeken.", exampleTranslation: "Ich lese gern Bücher." },
  { id: "de_a2_muziek",         level: "A2", topic: "Hobby's", dutch: "muziek",         german: "Musik",
    example: "Ik luister graag muziek.", exampleTranslation: "Ich höre gern Musik." },
  { id: "de_a2_voetbal",        level: "A2", topic: "Hobby's", dutch: "voetbal",        german: "Fußball",
    example: "Hij speelt graag voetbal.", exampleTranslation: "Er spielt gern Fußball." },
  { id: "de_a2_zwemmen",        level: "A2", topic: "Hobby's", dutch: "zwemmen",        german: "schwimmen" },
  { id: "de_a2_tekenen",        level: "A2", topic: "Hobby's", dutch: "tekenen",        german: "zeichnen" },
  { id: "de_a2_dansen",         level: "A2", topic: "Hobby's", dutch: "dansen",         german: "tanzen",
    example: "Ze danst elke week.", exampleTranslation: "Sie tanzt jede Woche." },
  { id: "de_a2_zingen",         level: "A2", topic: "Hobby's", dutch: "zingen",         german: "singen" },
  { id: "de_a2_fotograferen",   level: "A2", topic: "Hobby's", dutch: "fotograferen",   german: "fotografieren" },
  { id: "de_a2_wandelen",       level: "A2", topic: "Hobby's", dutch: "wandelen",       german: "wandern",
    example: "We wandelen in het weekend.", exampleTranslation: "Wir wandern am Wochenende." },
  { id: "de_a2_film",           level: "A2", topic: "Hobby's", dutch: "film",           german: "Film",
    example: "We kijken een film.", exampleTranslation: "Wir schauen einen Film." },

  // ── A2 · Lichaam ──────────────────────────────────────────────────────────
  { id: "de_a2_hoofd", level: "A2", topic: "Lichaam", dutch: "hoofd", german: "Kopf",
    example: "Mijn hoofd doet pijn.", exampleTranslation: "Mein Kopf tut weh." },
  { id: "de_a2_hand",  level: "A2", topic: "Lichaam", dutch: "hand",  german: "Hand" },
  { id: "de_a2_voet",  level: "A2", topic: "Lichaam", dutch: "voet",  german: "Fuß" },
  { id: "de_a2_oog",   level: "A2", topic: "Lichaam", dutch: "oog",   german: "Auge" },
  { id: "de_a2_oor",   level: "A2", topic: "Lichaam", dutch: "oor",   german: "Ohr" },
  { id: "de_a2_neus",  level: "A2", topic: "Lichaam", dutch: "neus",  german: "Nase" },
  { id: "de_a2_mond",  level: "A2", topic: "Lichaam", dutch: "mond",  german: "Mund" },
  { id: "de_a2_haar",  level: "A2", topic: "Lichaam", dutch: "haar",  german: "Haar" },
  { id: "de_a2_been",  level: "A2", topic: "Lichaam", dutch: "been",  german: "Bein" },
  { id: "de_a2_arm",   level: "A2", topic: "Lichaam", dutch: "arm",   german: "Arm" },
  { id: "de_a2_rug",   level: "A2", topic: "Lichaam", dutch: "rug",   german: "Rücken",
    example: "Ik heb rugpijn.", exampleTranslation: "Ich habe Rückenschmerzen." },

  // ── A2 · Tijd ─────────────────────────────────────────────────────────────
  { id: "de_a2_vandaag",   level: "A2", topic: "Tijd", dutch: "vandaag",   german: "heute",
    example: "Vandaag is het zaterdag.", exampleTranslation: "Heute ist Samstag." },
  { id: "de_a2_gisteren",  level: "A2", topic: "Tijd", dutch: "gisteren",  german: "gestern" },
  { id: "de_a2_morgen",    level: "A2", topic: "Tijd", dutch: "morgen",    german: "morgen",
    example: "Morgen is het zondag.", exampleTranslation: "Morgen ist Sonntag." },
  { id: "de_a2_nu",        level: "A2", topic: "Tijd", dutch: "nu",        german: "jetzt / nun" },
  { id: "de_a2_altijd",    level: "A2", topic: "Tijd", dutch: "altijd",    german: "immer",
    example: "Hij is altijd op tijd.", exampleTranslation: "Er ist immer pünktlich." },
  { id: "de_a2_nooit",     level: "A2", topic: "Tijd", dutch: "nooit",     german: "nie / niemals" },

  // ── B1 · Gevoelens ────────────────────────────────────────────────────────
  { id: "de_b1_blij",          level: "B1", topic: "Gevoelens", dutch: "blij",          german: "froh / fröhlich",
    example: "Ik ben erg blij met dit nieuws.", exampleTranslation: "Ich bin sehr froh über diese Neuigkeit." },
  { id: "de_b1_verdrietig",    level: "B1", topic: "Gevoelens", dutch: "verdrietig",    german: "traurig",
    example: "Ze was verdrietig na het nieuws.", exampleTranslation: "Sie war traurig nach der Nachricht." },
  { id: "de_b1_boos",          level: "B1", topic: "Gevoelens", dutch: "boos",          german: "wütend / böse",
    example: "Hij was boos om de vertraging.", exampleTranslation: "Er war wütend über die Verzögerung." },
  { id: "de_b1_bang",          level: "B1", topic: "Gevoelens", dutch: "bang",          german: "ängstlich / Angst haben" },
  { id: "de_b1_verrast",       level: "B1", topic: "Gevoelens", dutch: "verrast",       german: "überrascht",
    example: "Ik was aangenaam verrast.", exampleTranslation: "Ich war angenehm überrascht." },
  { id: "de_b1_moe",           level: "B1", topic: "Gevoelens", dutch: "moe",           german: "müde",
    example: "Ik ben erg moe vandaag.", exampleTranslation: "Ich bin heute sehr müde." },
  { id: "de_b1_nerveus",       level: "B1", topic: "Gevoelens", dutch: "nerveus",       german: "nervös" },
  { id: "de_b1_trots",         level: "B1", topic: "Gevoelens", dutch: "trots",         german: "stolz",
    example: "Ze is trots op haar werk.", exampleTranslation: "Sie ist stolz auf ihre Arbeit." },
  { id: "de_b1_teleurgesteld", level: "B1", topic: "Gevoelens", dutch: "teleurgesteld", german: "enttäuscht" },
  { id: "de_b1_opgewonden",    level: "B1", topic: "Gevoelens", dutch: "opgewonden",    german: "aufgeregt / begeistert" },

  // ── B1 · Technologie ──────────────────────────────────────────────────────
  { id: "de_b1_computer",    level: "B1", topic: "Technologie", dutch: "computer",    german: "Computer",
    example: "Mijn computer is kapot.", exampleTranslation: "Mein Computer ist kaputt." },
  { id: "de_b1_internet",    level: "B1", topic: "Technologie", dutch: "internet",    german: "Internet",
    example: "Het internet is traag vandaag.", exampleTranslation: "Das Internet ist heute langsam." },
  { id: "de_b1_smartphone",  level: "B1", topic: "Technologie", dutch: "smartphone",  german: "Smartphone" },
  { id: "de_b1_app",         level: "B1", topic: "Technologie", dutch: "app",         german: "App",
    example: "Er is een app voor alles.", exampleTranslation: "Es gibt eine App für alles." },

  // ── B1 · Samenleving (extra) ──────────────────────────────────────────────
  { id: "de_b1_burger",  level: "B1", topic: "Samenleving", dutch: "burger",  german: "Bürger / Bürgerin",
    example: "Elke burger heeft rechten.", exampleTranslation: "Jeder Bürger hat Rechte." },
  { id: "de_b1_wet",     level: "B1", topic: "Samenleving", dutch: "wet",     german: "Gesetz",
    example: "Je moet je aan de wet houden.", exampleTranslation: "Du musst dich an das Gesetz halten." },
  { id: "de_b1_recht",   level: "B1", topic: "Samenleving", dutch: "recht",   german: "Recht",
    example: "Iedereen heeft recht op onderwijs.", exampleTranslation: "Jeder hat das Recht auf Bildung." },
  { id: "de_b1_plicht",  level: "B1", topic: "Samenleving", dutch: "plicht",  german: "Pflicht",
    example: "Stemmen is een burgerplicht.", exampleTranslation: "Wählen ist eine Bürgerpflicht." },

  // ── B2 · Abstracte concepten ─────────────────────────────────────────────
  { id: "de_b2_waarheid",           level: "B2", topic: "Abstracte concepten", dutch: "waarheid",           german: "Wahrheit",
    example: "De waarheid is soms moeilijk.", exampleTranslation: "Die Wahrheit ist manchmal schwierig." },
  { id: "de_b2_kennis",             level: "B2", topic: "Abstracte concepten", dutch: "kennis",             german: "Wissen / Kenntnisse",
    example: "Kennis is macht.", exampleTranslation: "Wissen ist Macht." },
  { id: "de_b2_macht",              level: "B2", topic: "Abstracte concepten", dutch: "macht",              german: "Macht",
    example: "Macht corrumpeert.", exampleTranslation: "Macht korrumpiert." },
  { id: "de_b2_verantwoordelijkheid", level: "B2", topic: "Abstracte concepten", dutch: "verantwoordelijkheid", german: "Verantwortung",
    example: "We hebben een verantwoordelijkheid jegens de toekomst.", exampleTranslation: "Wir haben eine Verantwortung gegenüber der Zukunft." },
  { id: "de_b2_risico",             level: "B2", topic: "Abstracte concepten", dutch: "risico",             german: "Risiko",
    example: "Dit is een groot risico.", exampleTranslation: "Das ist ein großes Risiko." },
  { id: "de_b2_invloed",            level: "B2", topic: "Abstracte concepten", dutch: "invloed",            german: "Einfluss",
    example: "Sociale media hebben veel invloed.", exampleTranslation: "Soziale Medien haben viel Einfluss." },
  { id: "de_b2_identiteit",         level: "B2", topic: "Abstracte concepten", dutch: "identiteit",         german: "Identität",
    example: "Culturele identiteit is belangrijk.", exampleTranslation: "Kulturelle Identität ist wichtig." },
  { id: "de_b2_cultuur",            level: "B2", topic: "Abstracte concepten", dutch: "cultuur",            german: "Kultur",
    example: "Elke cultuur is uniek.", exampleTranslation: "Jede Kultur ist einzigartig." },
  { id: "de_b2_traditie",           level: "B2", topic: "Abstracte concepten", dutch: "traditie",           german: "Tradition",
    example: "Die traditie stamt uit de middeleeuwen.", exampleTranslation: "Diese Tradition stammt aus dem Mittelalter." },

  // ── B2 · Bedrijfsleven ────────────────────────────────────────────────────
  { id: "de_b2_bedrijf",     level: "B2", topic: "Bedrijfsleven", dutch: "bedrijf",     german: "Unternehmen / Firma",
    example: "Hij leidt een groot bedrijf.", exampleTranslation: "Er leitet ein großes Unternehmen." },
  { id: "de_b2_winst",       level: "B2", topic: "Bedrijfsleven", dutch: "winst",       german: "Gewinn",
    example: "Het bedrijf maakt winst.", exampleTranslation: "Das Unternehmen macht Gewinn." },
  { id: "de_b2_verlies",     level: "B2", topic: "Bedrijfsleven", dutch: "verlies",     german: "Verlust",
    example: "Ze leden grote verliezen.", exampleTranslation: "Sie erlitten große Verluste." },
  { id: "de_b2_investering", level: "B2", topic: "Bedrijfsleven", dutch: "investering", german: "Investition",
    example: "Dat is een goede investering.", exampleTranslation: "Das ist eine gute Investition." },
  { id: "de_b2_markt",       level: "B2", topic: "Bedrijfsleven", dutch: "markt",       german: "Markt",
    example: "De markt is onzeker.", exampleTranslation: "Der Markt ist ungewiss." },
  { id: "de_b2_fusie",       level: "B2", topic: "Bedrijfsleven", dutch: "fusie",       german: "Fusion / Übernahme",
    example: "De fusie werd goedgekeurd.", exampleTranslation: "Die Fusion wurde genehmigt." },

  // ── B2 · Milieu (extra) ───────────────────────────────────────────────────
  { id: "de_b2_uitstoot",     level: "B2", topic: "Milieu", dutch: "uitstoot",     german: "Emission / Ausstoß",
    example: "De uitstoot van CO₂ moet dalen.", exampleTranslation: "Der CO₂-Ausstoß muss sinken." },
  { id: "de_b2_afval",        level: "B2", topic: "Milieu", dutch: "afval",        german: "Abfall / Müll",
    example: "We moeten minder afval produceren.", exampleTranslation: "Wir müssen weniger Müll produzieren." },
  { id: "de_b2_energie",      level: "B2", topic: "Milieu", dutch: "energie",      german: "Energie",
    example: "Zonne-energie is duurzaam.", exampleTranslation: "Solarenergie ist nachhaltig." },
  { id: "de_b2_hernieuwbaar", level: "B2", topic: "Milieu", dutch: "hernieuwbaar", german: "erneuerbar",
    example: "Hernieuwbare energie is de toekomst.", exampleTranslation: "Erneuerbare Energie ist die Zukunft." },

  // ── C1 · Recht & ethiek ───────────────────────────────────────────────────
  { id: "de_c1_rechtbank",  level: "C1", topic: "Recht & ethiek", dutch: "rechtbank",  german: "Gericht",
    example: "De zaak gaat naar de rechtbank.", exampleTranslation: "Der Fall geht vor Gericht." },
  { id: "de_c1_vonnis",     level: "C1", topic: "Recht & ethiek", dutch: "vonnis",     german: "Urteil",
    example: "Het vonnis was zwaar.", exampleTranslation: "Das Urteil war schwer." },
  { id: "de_c1_advocaat",   level: "C1", topic: "Recht & ethiek", dutch: "advocaat",   german: "Anwalt / Anwältin",
    example: "Ze heeft een advocaat ingehuurd.", exampleTranslation: "Sie hat einen Anwalt engagiert." },
  { id: "de_c1_aanklacht",  level: "C1", topic: "Recht & ethiek", dutch: "aanklacht",  german: "Anklage",
    example: "Er is een aanklacht ingediend.", exampleTranslation: "Eine Anklage wurde eingereicht." },
  { id: "de_c1_onschuld",   level: "C1", topic: "Recht & ethiek", dutch: "onschuld",   german: "Unschuld",
    example: "Hij bewees zijn onschuld.", exampleTranslation: "Er bewies seine Unschuld." },
  { id: "de_c1_grondwet",   level: "C1", topic: "Recht & ethiek", dutch: "grondwet",   german: "Verfassung / Grundgesetz",
    example: "De grondwet beschermt onze rechten.", exampleTranslation: "Das Grundgesetz schützt unsere Rechte." },

  // ── C1 · Literatuur ───────────────────────────────────────────────────────
  { id: "de_c1_roman",      level: "C1", topic: "Literatuur", dutch: "roman",      german: "Roman",
    example: "Hij schrijft een historische roman.", exampleTranslation: "Er schreibt einen historischen Roman." },
  { id: "de_c1_gedicht",    level: "C1", topic: "Literatuur", dutch: "gedicht",    german: "Gedicht",
    example: "Het gedicht heeft een rijmschema.", exampleTranslation: "Das Gedicht hat ein Reimschema." },
  { id: "de_c1_metafoor",   level: "C1", topic: "Literatuur", dutch: "metafoor",   german: "Metapher",
    example: "De metafoor versterkt de betekenis.", exampleTranslation: "Die Metapher verstärkt die Bedeutung." },
  { id: "de_c1_personage",  level: "C1", topic: "Literatuur", dutch: "personage",  german: "Figur / Charakter",
    example: "Het hoofdpersonage evolueert sterk.", exampleTranslation: "Die Hauptfigur entwickelt sich stark." },
  { id: "de_c1_vert_roman", level: "C1", topic: "Literatuur", dutch: "verteller",  german: "Erzähler / Erzählerin",
    example: "De verteller is anoniem.", exampleTranslation: "Der Erzähler ist anonym." },

  // ── C1 · Wetenschap ───────────────────────────────────────────────────────
  { id: "de_c1_hypothese",  level: "C1", topic: "Wetenschap", dutch: "hypothese",  german: "Hypothese",
    example: "De hypothese werd getest.", exampleTranslation: "Die Hypothese wurde getestet." },
  { id: "de_c1_experiment", level: "C1", topic: "Wetenschap", dutch: "experiment", german: "Experiment",
    example: "Het experiment leverde verrassende resultaten.", exampleTranslation: "Das Experiment lieferte überraschende Ergebnisse." },
  { id: "de_c1_bewijs",     level: "C1", topic: "Wetenschap", dutch: "bewijs",     german: "Beweis",
    example: "Er is geen wetenschappelijk bewijs.", exampleTranslation: "Es gibt keinen wissenschaftlichen Beweis." },
  { id: "de_c1_theorie",    level: "C1", topic: "Wetenschap", dutch: "theorie",    german: "Theorie",
    example: "Dat is slechts een theorie.", exampleTranslation: "Das ist nur eine Theorie." },
  { id: "de_c1_onderzoek",  level: "C1", topic: "Wetenschap", dutch: "onderzoek",  german: "Forschung / Untersuchung",
    example: "Het onderzoek duurt jaren.", exampleTranslation: "Die Forschung dauert Jahre." },

  // ── C1 · Taal (extra) ─────────────────────────────────────────────────────
  { id: "de_c1_grammatica",   level: "C1", topic: "Taal", dutch: "grammatica",   german: "Grammatik",
    example: "Duitse grammatica is complex.", exampleTranslation: "Deutsche Grammatik ist komplex." },
  { id: "de_c1_uitspraak",    level: "C1", topic: "Taal", dutch: "uitspraak",    german: "Aussprache",
    example: "Zijn uitspraak is uitstekend.", exampleTranslation: "Seine Aussprache ist ausgezeichnet." },
  { id: "de_c1_woordenschat", level: "C1", topic: "Taal", dutch: "woordenschat", german: "Wortschatz",
    example: "Ze heeft een grote woordenschat.", exampleTranslation: "Sie hat einen großen Wortschatz." },
  { id: "de_c1_zin",          level: "C1", topic: "Taal", dutch: "zin",          german: "Satz",
    example: "De zin is te lang.", exampleTranslation: "Der Satz ist zu lang." },
  { id: "de_c1_vertaling",    level: "C1", topic: "Taal", dutch: "vertaling",    german: "Übersetzung",
    example: "De vertaling is accuraat.", exampleTranslation: "Die Übersetzung ist akkurat." },

  // ── C1 · Maatschappij (extra) ─────────────────────────────────────────────
  { id: "de_c1_solidariteit", level: "C1", topic: "Maatschappij", dutch: "solidariteit", german: "Solidarität",
    example: "Solidariteit is essentieel in crisistijden.", exampleTranslation: "Solidarität ist in Krisenzeiten wesentlich." },

];
